### PR TITLE
feat: Add akmods module

### PR DESCRIPTION
**Pull request by fiftydinar**
Credits: @C0dePlayer

This is not ideal as it does not support custom kernels & it involves editing Containerfile.

Custom kernels is something that upstream should solve I believe, so it's not a concern we should direct to.

I believe there is no other way but to make users edit Containerfile for those files to be even pulled of.

I would like this to be through the recipe only, so I will put this as a draft until some better ideas come.

2nd part of this work:
https://github.com/ublue-os/bling/pull/89

### CODE REVIEW

**Comment by xynydev** [comment]
How big are the akmods, like, would it hurt to just always COPY them in the Containerfile (as is done with bling rpms and files). This would make just the module be used to configure akmods installation.

Also, the tag part could be `main-${IMAGE_MAJOR_VERSION}`, but if someone wanted to build main, asus & surface images they'd need to edit build.yml...

**Comment by fiftydinar** [comment]
> How big are the akmods, like, would it hurt to just always COPY them in the Containerfile (as is done with bling rpms and files). This would make just the module be used to configure akmods installation.

It's 2MB when I pulled it with podman. Not big imo

Screenshot from 2023-12-27 10-39-59

**Comment by xynydev** [comment]
Then I'd probably pull main by default and just document it well that you need to change that if you're building asus or surface.

**Comment by fiftydinar** [comment]
> Then I'd probably pull main by default and just document it well that you need to change that if you're building asus or surface.

That's only needed if users want to use older version of Fedora as a base (GTS as the most used option of those).

Users can use -nvidia, -asus, -surface etc. builds as a base if they want those akmods.

I did the change to address this:
https://github.com/ublue-os/bling/blob/d76cca4f3abc7e0730c45e3d820d36b236194c89/modules/akmods/README.md

**Comment by fiftydinar** [comment]
> How big are the akmods, like, would it hurt to just always COPY them in the Containerfile (as is done with bling rpms and files). This would make just the module be used to configure akmods installation.
> 
> Also, the tag part could be `main-${IMAGE_MAJOR_VERSION}`, but if someone wanted to build main, asus & surface images they'd need to edit build.yml...

I forgot to mention, when I set ${IMAGE_MAJOR_VERSION}, it fails

The guy who originally made akmods module used this workaround:

https://github.com/C0dePlayer/silverflow/blob/live/Containerfile

**Comment by fiftydinar** [comment]
Adding IMAGE_MAJOR_VERSION as an argument only works when building an image offline. Github Action fails.

So I think it's good as it is (2nd part of the PR still needs some fixes though).

It's a shame that akmods repo doesn't have `latest` tag available though. So you need to edit this manually whenever new Fedora gets a release. I filled an issue on this.

**Comment by fiftydinar** [comment]
If this "latest" tag is not considered in akmods repo, I believe this is ready to merge, as 2nd part in bling is finally ready.

**Review by xynydev — APPROVED** [review]

**Comment by xynydev** [comment]
To merge, please update the branch @fiftydinar

**Comment by fiftydinar** [comment]
> To merge, please update the branch @fiftydinar

Updated

**Pull request merged**
