### PR TITLE
feat: add just syntax checker

### PR DESCRIPTION
**Pull request by ArtikusHG**
Integrate our new [just syntax checker](https://github.com/ublue-os/just-action) into the build action.

I assume this is the last repo that needs this, but if I missed anything, let me know!

### CODE REVIEW

**Comment by xynydev** [comment]
Does this action check files in a specific directory, or just the ones matching with `*.just`? 

Edit: seems to be the ones matching `*.just`. I guess I'll approve, then.

**Review by xynydev — APPROVED** [review]

**Comment by ArtikusHG** [comment]
@xynydev yes, this checks for all .just files in the repo

**Comment by ArtikusHG** [comment]
This seems to be failing because ``config/files/usr/share/ublue-os/just/60-custom.just`` contains ``!include /usr/share/ublue-os/just/100-bling.just``, which does not exist, which triggers an error in just. I think we should probably just create an empty file with that name? @xynydev does that seem like a valid solution for you?

EDIT: just realized that's a bigger problem than it seems - in the system, the file is in ``/usr``, but in the repo, it is in ``config/files/usr``, so that will always trigger an error, even if we do create that file. As a workaround, we could link ``config/files/usr`` to the root directory (either in the repo or during buildtime in the action), so that if a justfile is included, the check doesn't fail.

EDIT 2: wouldn't changing ``!include /usr/share/ublue-os/just/100-bling.just`` to be simply ``!include 100-bling.just`` also work? Both of these files are in the same directory.

The just docs say the following:

> The !include directive path can be absolute or relative to the location of the justfile containing it. !include directives must appear at the beginning of a line.

I think this solution is the one we should go with (create an empty file with that name and change the path to be relative instead of absolute).

**Comment by ArtikusHG** [comment]
Took a bit of trial and error, but this now passes the syntax check (tested by triggering the workflow in my fork).

**Comment by xynydev** [comment]
Why'd that fail? I think it's a worthwile effort to document the file's existence. Local --fmt --check 's don't cause failure for me...

**Comment by ArtikusHG** [comment]
@xynydev try running just --fmt before commit, just seems to be very picky

**Comment by xynydev** [comment]
> just seems to be very picky

That'll get annoying...

**Pull request merged**
