### PR TITLE
fix: dont add malformed tags if $MAJOR_VERSION is empty

### PR DESCRIPTION
**Pull request by xynydev**
Re: #140 
Can @Waffleophagus, @Amcolex and whoever else was having this problem report if this fix helps, and someone with review perms approve this.

### CODE REVIEW

**Comment by amcolex** [comment]
Doesn't look like it: https://github.com/Amcolex/ublue-hyprland/actions/runs/5870406932/job/15917362078

**Comment by xynydev** [comment]
@Amcolex that looks like a different error than what I was seeing in waffle's repo.

**Comment by amcolex** [comment]
Yea, i see that the negative date is gone. but it still seems linked to the date format:

invalid reference format time="2023-08-15T22:24:35Z"

Honestly i have no idea whats going on here, and why it only affects me.

**Comment by Waffleophagus** [comment]
@Amcolex it doesn’t only effect you, I was running into this as well, my temp fix worked for me but wanna help get a “proper” fix. @EinoHR ill have time tonight to dig in and see if this fix tackles my issue. If you want to reach out on discord too I’ll be available more synchronously too if you want.

**Comment by Waffleophagus** [comment]
@EinoHR https://github.com/Waffleophagus/WafflOSagus/actions/runs/5885219567/job/15961320926 I believe this fixed my issue, you want me to test any other weirdish cases?

**Comment by xynydev** [comment]
> I believe this fixed my issue, you want me to test any other weirdish cases?

Great, I'll have this PR approved by somebody then. If the other issue still plagues you and you suspect that it is a fault in the template, please file a Github issue and we'll investigate together. While you can also ping on discord, but that probably wont make me respond quicker.

**Review by akdev1l — APPROVED** [review]

**Pull request merged**
