### PR TITLE
feat: add extra repos field to recipe

### PR DESCRIPTION
**Pull request by EinoHR**
#35

### CODE REVIEW

**Comment by federdaemn** [comment]
I think a variabel for the current fedora version should be introduced. Then we only need to change one thing for a version upgrade and not all repos.

**Comment by EinoHR** [comment]
Will merge if this build in my repo works https://github.com/EinoHR/linuXYZ/actions/runs/4820959574/jobs/8586161155

**Comment by EinoHR** [comment]
> I think a variabel for the current fedora version should be introduced. Then we only need to change one thing for a version upgrade and not all repos.

Good idea, I'll only do it in a seperate PR though as I have to figure out the implementation details.

**Comment by EinoHR** [comment]
Fixed by [3f4c71c](https://github.com/ublue-os/startingpoint/pull/52/commits/3f4c71cfb9d7a33626cb28fb9f08c89b8a110100)

**Pull request merged**
