### PR TITLE
give /usr/bin/ublue-nix-install executable permission

### PR DESCRIPTION
**Pull request by fenglengshun**
From checking my system and repo, it seems that ublue-nix-install lacks an execution permission:

```
$ exa -al ./usr/bin/ublue-nix-install
.rw-r--r--@ 4.2k fenglengshun 24 May 21:37  ./usr/bin/ublue-nix-install

``` 

So I did a `chmod a+x ./usr/bin/ublue-nix-install` to give it execution permission. Please tell me if there's any issue, this is my first time making a PR (total github newbie).

### CODE REVIEW

**Comment by fenglengshun** [comment]
Apparently it is currently intentionally disabled:

[image](https://discordapp.com/channels/1072614816579063828/1072617059265032342/1110943362594394154)

New repo: https://github.com/dnkmmr69420/nix-installer-scripts

**Comment by Arcitec** [comment]
> New repo: https://github.com/dnkmmr69420/nix-installer-scripts

Yeah that's the new repo, thanks for digging up the URL!

Since I don't use the Nix feature myself I haven't looked deeper into the appropriate action here. The new script is more complex, [does realtime imports of other scripts directly from the internet](https://github.com/dnkmmr69420/nix-installer-scripts/blob/main/installer-scripts/silverblue-nix-installer.sh), etc.

So I dunno what to do here. We try to be secure by only shipping scripts that are predictable, and packages that are maintained by Fedora.

One way to make it predictable would be to import all of the new scripts (even the stuff it downloads in realtime) and then maintain a copy here that only runs local scripts, but again, someone with interest in Nix would have to make that call... :)

Edit: As for the outdated script we currently ship (which the script author called "broken"), I would be in favor of removing it, but I have no investment in Nix so yet again it's not my call to make...

**Comment by fenglengshun** [comment]
> Edit: As for the outdated script we currently ship (which the script author called "broken"), I would be in favor of removing it, but I have no investment in Nix so yet again it's not my call to make...

I'm personally in favor of removing it for now, as well as either removing or commenting out the `nix-me-up` just command in `/usr/share/ublue-os/just/custom.just`, with the perspective of "the noob who doesn't realize the reason why it was disabled, trying to run it manually."

**Comment by fenglengshun** [comment]
Update, I've tested the script from https://github.com/dnkmmr69420/nix-installer-scripts, specifically this one:

```
curl -s https://raw.githubusercontent.com/dnkmmr69420/nix-installer-scripts/main/installer-scripts/silverblue-nix-installer.sh | bash
```

It seems to work fine, I can install my home-manager and proceed to restore my home.nix setup just fine. The only issue was that during a switch process, my internet connection cuts off, and I had to do `export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}` before doing `home-manager switch`, but that's not an issue with the script as I have had similar issues on other systems as well before.

From a user-facing perspective, the output seems pretty clear in explaining what it does when you're running it. So I'm of the opinion that `just nix-me-up` to simply ask:

```
This will install nix to your system using the script by dnkmmr69420 at https://github.com/dnkmmr69420/nix-installer-scripts
You can check the content for this script here: https://raw.githubusercontent.com/dnkmmr69420/nix-installer-scripts/main/installer-scripts/silverblue-nix-installer.sh
Continue setting up nix? [y/N]
```

And then proceed to execute that script through curl. Thoughts?

**Comment by xynydev** [comment]
Sure, I'd be up for removing the nix-me-up from startingpoint and adding a recipe like that to the config repo.
I recently used `just nix-me-up` to install Nix on my computer and it worked perfectly, so I don't know what the issue is there, but using the authors own repo is probably better anyway.

**Pull request closed without merging**
