### PR TITLE
chore: Update recipe file with all modules

### PR DESCRIPTION
**Pull request by fiftydinar**
This awaits approval of this:

https://github.com/ublue-os/bling/pull/88

for additional systemd module option (masked).

### CODE REVIEW

**Comment by xynydev** [comment]
I somewhat disagree with the premise of this PR:
- It changes the recipe.yml, creating merge conflicts for every user
- It sets up a premise for frequent updates to the default recipe.yml, creating even more merge conflicts in the long run
- It clutters the recipe.yml, including every module by default when most users wont need to use every module
   - IMO adding a module to your recipe.yml should be something you do explicitly, and even the yafti module might be worth removing from the default configuration (once it is changed to not require a yafti.yml existing in the repo)

**Comment by fiftydinar** [comment]
> I somewhat disagree with the premise of this PR:
> 
>     * It changes the recipe.yml, creating merge conflicts for every user
> 
>     * It sets up a premise for frequent updates to the default recipe.yml, creating even more merge conflicts in the long run
> 
>     * It clutters the recipe.yml, including every module by default when most users wont need to use every module
>       
>       * IMO adding a module to your recipe.yml should be something you do explicitly, and even the yafti module might be worth removing from the default configuration (once it is changed to not require a yafti.yml existing in the repo)

I agree when you mentioned merge conflicts. I thought to include all of those, so users would know what startingpoint is capable of.

I agree it looks cluttered. Original recipe is already alright with predefined options.

Maybe in the future, we can split those options separately in common_modules folder? Like rpm-ostree.yml, default-flatpaks.yml, bling.yml etc
That looks cleaner imo.

It will make a merge conflict, but almost any change to startingpoint is making this. So it's just a question is it worth to do that or not.

**Comment by xynydev** [comment]
> Maybe in the future, we can split those options separately in common_modules folder? Like rpm-ostree.yml, default-flatpaks.yml, bling.yml etc
That looks cleaner imo.

I agree that it looks better, but for I disagree about using it for the default config. Many people make custom images where the configuration easily fits in one file and there's only one edition. The default recipe could be updated, though, so that it showcases the from-file option commented out, and I'd probably replace yafti with default-flatpaks too.

**Comment by fiftydinar** [comment]
> > Maybe in the future, we can split those options separately in common_modules folder? Like rpm-ostree.yml, default-flatpaks.yml, bling.yml etc
> > That looks cleaner imo.
> 
> I agree that it looks better, but for I disagree about using it for the default config. Many people make custom images where the configuration easily fits in one file and there's only one edition. The default recipe could be updated, though, so that it showcases the from-file option commented out, and I'd probably replace yafti with default-flatpaks too.

I can make those changes if you agree in the end. I think that's a good suggestion.

**Pull request closed without merging**
