### PR TITLE
fix!: moving component files to the new, standardized location

### PR DESCRIPTION
**Pull request by Arcitec**
~~This is a work in progress.~~

I did this now since bikeshedding is boring and many eyes have been on the proposal with zero interjections, so to get the ball rolling, here's the first pull request.

Ready for merge.

The following files are now corrected:

```
/usr/share/ublue-os/
  ├── firstboot
zz│   │── ublue-firstboot.desktop
x │   └── yafti.yml
x │── just
x │   └── justfile
yy│── update-services
yy│   └── etc
yy│       └── rpm-ostreed.conf
x └── recipe.yml
```

- x = done
- zz = depends on a larger improvement to the first-boot system, will be done in a separate pull request after this is merged
- yy = needs doing in other repo (that fix belongs to "[main](https://github.com/ublue-os/main/blob/main/post-install.sh#L10)")

### CODE REVIEW

**Comment by EinoHR** [comment]
Please see the newest comments at https://github.com/orgs/ublue-os/discussions/149#discussioncomment-5862855

**Review by EinoHR — CHANGES_REQUESTED** [review]
[As discussed](https://github.com/orgs/ublue-os/discussions/149#discussioncomment-5864201), move justfile to `/usr/share/ublue-os/just/justfile`

**Comment by Arcitec** [comment]
> [As discussed](https://github.com/orgs/ublue-os/discussions/149#discussioncomment-5864201), move justfile to `/usr/share/ublue-os/just/justfile`

Yep, already did that change. :)

Just finished rebasing it onto main. It's ready.

**Review by EinoHR — APPROVED** [review]

**Comment by Arcitec** [comment]
@EinoHR Regarding `ublue-firstboot`, I will work on that tomorrow evening (sometime after 18:00 GMT). It's going to be a larger change to how that's executed. I need to rest today since I have an important appointment tomorrow. :) But that will soon be fixed too. Then the startingpoint repo will be fully transitioned.

**Pull request merged**
